<?php
/**
use Drupal\Core\Entity\EntityInterface;

const PRESENTATION_TYPE = '1060';
const SLIDESHARE_API_KEY = '';
const SLIDESHARE_SHARED_SECRET = '';


 * hook_ENTITY_TYPE_update()
 *
 * call Slideshare webservice to get the id
 *

function cgspace_importer_node_update(EntityInterface $entity) {

  if($entity->bundle() === 'publication') {

    $type_tid = $entity->get('field_publication_type_ref')->getValue();

    if (isset($type_tid[0]['target_id']) && ($type_tid[0]['target_id'] === PRESENTATION_TYPE)) {

      $slideshare_id = $entity->get('field_slideshare_id')->getValue();

      if (!isset($slideshare_id[0]['value'])) {

        $links_field = $entity->get('field_link_document')->getValue();
        if (is_array($links_field)) {
          foreach ($links_field as $link) {
            if (isset($link['uri']) && (str_contains($link['uri'], 'slideshare.net') === TRUE)) {

              try {
                $timestamp = time();
                $response = \Drupal::httpClient()
                  ->get('https://www.slideshare.net/api/2/get_slideshow', [
                    'api_key' => SLIDESHARE_API_KEY,
                    'ts' => $timestamp,
                    'hash' => sha1($timestamp.SLIDESHARE_SHARED_SECRET),
                    'slideshow_url' => $link['uri'],
                    'detailed' => 1
                  ]);

                dpm($response->getBody());
              }
              catch (Exception $e) {
                \Drupal::logger('cgspace_importer')->error(t('Unable to get Slideshare ID: @error', ['@error' => $e->getMessage()]));
              }
            }
          }
        }
      }
    }
  }

}
 */
